name: Build and Publish Executables

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build-and-publish.yml'
      - 'src/**'
      - '!src/AppServiceSidecars.Core.Tests/**'

  pull_request:
    branches:
      - main
    paths:
      - 'src/**'
      - '!src/AppServiceSidecars.Core.Tests/**'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: Restore dependencies
      run: dotnet restore src/AppServiceSidecars.sln

    - name: Build project
      run: dotnet build src/AppServiceSidecars.sln --configuration Release

    - name: Publish executables
      shell: bash
      run: |
        dotnet publish src/AppServiceSidecars.Cli/AppServiceSidecarsCli.csproj \
          --configuration Release \
          --runtime ${{ matrix.os == 'ubuntu-latest' && 'linux-x64' || 'win-x64' }} \
          --self-contained true \
          --output ./publish/${{ matrix.os }}

    - name: Upload artifact
      uses: actions/upload-artifact@v4.6.2
      with:
        name: AppServiceSidecars-${{ matrix.os }}
        path: ./publish/${{ matrix.os }}
